# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt



Street_Name='SIDNEY COVE DRIVE'&Parish='TRELAWNY'
https://data.gov.jm/api/action/datastore/search.json?Street_Name="SIDNEY COVE DRIVE" &Parish="TRELAWNY"


https://data.gov.jm/api/action/datastore/search.json?resource_id=6fe1e0b6-e429-4d10-b6be-3822e7032a27&Street_Name="SIDNEY COVE DRIVE" &Parish="TRELAWNY"


SIDNEY COVE DRIVE, TRELAWNY


Write a script for ArGIS ApI for Python to access ArcGIS Enterprise, download records and upload the records to a Postgresql database.




(IATA: PTY, ICAO: MPTO) is the primary international airport serving Panama City, the capital of Panama. The airport serves as the homebase for Copa Airlines and is a regional hub to and from The Caribbean, South, North and Central America and additionally features routes to some European and Asian cities.

